import os
import xml.etree.ElementTree as ET
import requests
from requests.auth import HTTPBasicAuth
import json

JIRA_URL = os.getenv("JIRA_URL")
RTM_TOKEN = os.getenv("RTM_API_KEY")
JIRA_USER = os.getenv("JIRA_USER")
PROJECT_KEY = os.getenv("JIRA_PROJECT", "QA")

JUNIT_FILE = "report/junit.xml"
PDF_REPORT = "report/test_result_report.pdf"
HTML_REPORT = "report/test_result_report.html"


def auth():
    return HTTPBasicAuth(JIRA_USER, RTM_TOKEN)


# =============================================
# 1. Parse JUnit XML
# =============================================
def parse_junit():
    tree = ET.parse(JUNIT_FILE)
    root = tree.getroot()

    tests = []
    for tc in root.iter("testcase"):
        name = tc.get("name")
        classname = tc.get("classname")
        time_taken = tc.get("time")
        full_path = f"{classname}::{name}"

        # Determine status
        status = "PASS"
        if tc.find("failure") is not None:
            status = "FAIL"
        if tc.find("error") is not None:
            status = "ERROR"
        if tc.find("skipped") is not None:
            status = "SKIPPED"

        tests.append({
            "name": name,
            "path": full_path,
            "duration": time_taken,
            "status": status
        })

    return tests


# =============================================
# 2. Create RTM Test Case
# =============================================
def create_rtm_testcase(test):
    url = f"{JIRA_URL}/rest/atm/1.0/testcase"

    test_steps = [{
        "description": f"Autogenerated test: {test['name']}",
        "expectedResult": "Refer automation result"
    }]

    payload = {
        "projectKey": PROJECT_KEY,
        "name": test["name"],
        "objective": "Automatically created from pytest",
        "status": "Approved",
        "script": {
            "type": "AUTOMATED",
            "location": test["path"]
        },
        "steps": test_steps
    }

    res = requests.post(url, auth=auth(), json=payload)
    res.raise_for_status()

    key = res.json()["key"]
    print(f"✔ Created RTM Test Case: {key}")
    return key


# =============================================
# 3. Create Test Execution
# =============================================
def create_test_execution():
    url = f"{JIRA_URL}/rest/atm/1.0/testexecutions"
    payload = {
        "projectKey": PROJECT_KEY,
        "name": "Automated Execution (Pytest Auto-Creation)",
        "description": "Generated automatically from Jenkins + Pytest"
    }
    res = requests.post(url, auth=auth(), json=payload)
    res.raise_for_status()
    exec_key = res.json()["key"]
    print(f"✔ Created Test Execution: {exec_key}")
    return exec_key


# =============================================
# 4. Add Test Case to Execution
# =============================================
def add_test_to_execution(exec_key, test_key):
    url = f"{JIRA_URL}/rest/atm/1.0/testexecutions/{exec_key}/testcases"
    payload = {"add": [test_key]}

    res = requests.post(url, auth=auth(), json=payload)
    res.raise_for_status()
    print(f"→ Added {test_key} to execution {exec_key}")


# =============================================
# 5. Upload Automated Results
# =============================================
def upload_test_result(exec_key, test_key, status):
    url = f"{JIRA_URL}/rest/atm/1.0/testrun"
    payload = {
        "projectKey": PROJECT_KEY,
        "testExecKey": exec_key,
        "testCaseKey": test_key,
        "status": status
    }

    res = requests.post(url, auth=auth(), json=payload)
    res.raise_for_status()
    print(f"✔ Updated result for {test_key}: {status}")


# =============================================
# 6. Attach PDF & HTML
# =============================================
def attach_report(issue_key, path):
    url = f"{JIRA_URL}/rest/api/3/issue/{issue_key}/attachments"
    headers = {"X-Atlassian-Token": "no-check"}

    with open(path, "rb") as f:
        files = {"file": (os.path.basename(path), f)}
        res = requests.post(url, headers=headers, auth=auth(), files=files)
        res.raise_for_status()

    print(f"📎 Attached {path}")


# =============================================
# MAIN WORKFLOW
# =============================================
def main():
    print("\n🔍 Parsing JUnit XML ...")
    tests = parse_junit()

    print("\n📝 Creating RTM Test Cases ...")
    mapping = {}  # pytest test → RTM key

    for test in tests:
        key = create_rtm_testcase(test)
        mapping[test["name"]] = key

    print("\n📌 Creating Test Execution ...")
    exec_key = create_test_execution()

    print("\n🔗 Linking Test Cases to Execution ...")
    for test in tests:
        add_test_to_execution(exec_key, mapping[test["name"]])

    print("\n📤 Uploading Test Results ...")
    for test in tests:
        upload_test_result(exec_key, mapping[test["name"]], test["status"])

    print("\n📎 Attaching Reports ...")
    if os.path.exists(PDF_REPORT):
        attach_report(exec_key, PDF_REPORT)

    if os.path.exists(HTML_REPORT):
        attach_report(exec_key, HTML_REPORT)

    print("\n🎉 Completed full RTM automation workflow!\n")


if __name__ == "__main__":
    main()
